name: Linter

on: [push, pull_request]

env:
  PYTHON_VERSION: "3.12"
  UV_VERSION: "0.7.8"
  UV_PROJECT_ENVIRONMENT: .venv
  RUFF_VERSION: "0.11.2"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    strategy:
      fail-fast: true
      matrix:
        project:
          - thirdweb-ai
          - thirdweb-mcp

    name: Linter (${{ matrix.project }})
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python/${{ matrix.project }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174 # v5

      - name: Install Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          cache: true
          cache-dependency-path: "python/${{ matrix.project }}/uv.lock" # Update cache if uv.lock changes

      - name: Install the project
        run: uv sync --group dev --all-extras

      - name: Configure path
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Run Ruff linter
        run: uv run ruff check --output-format=github .

      - name: Run Ruff formatter
        run: uv run ruff format --check .

      - name: Run Pyright check
        run: uv run pyright src/
