name: Publish thirdweb MCP to PyPI

on:
  workflow_dispatch:

jobs:
  deploy-pypi-thirdweb-mcp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python/thirdweb-mcp
    environment:
      name: pypi
      url: https://pypi.org/p/thirdweb-mcp
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Install Poetry
      run: pipx install poetry==1.8.5

    - name: Set up Python 3.10
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: '3.10'
        cache: 'poetry'

    - name: Install dependencies
      run: poetry install --only main

    - name: Build package
      run: poetry build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_KEY }}
        packages-dir: python/thirdweb-mcp/dist/
