name: Publish thirdweb AI to PyPI

on:
  workflow_dispatch:

jobs:
  deploy-pypi-thirdweb-ai:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python/thirdweb-ai
    environment:
      name: pypi
      url: https://pypi.org/p/thirdweb-ai
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Install uv
      uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174 # v5

    - name: Install Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock" # Update cache if uv.lock changes

    - name: Install the project
      run: uv sync

    - name: Build package
      run: uv build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_KEY }}
        packages-dir: python/thirdweb-ai/dist/
