name: Publish thirdweb AI to PyPI

on:
  workflow_dispatch:

jobs:
  deploy-pypi-thirdweb-ai:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python/thirdweb-ai
    environment:
      name: pypi
      url: https://pypi.org/p/thirdweb-ai
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: poetry install --only main

    - name: Build package
      run: poetry build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_KEY }}
        packages-dir: python/thirdweb-ai/dist/