name: Build and Publish

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174 # v5

      - name: Install Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock" # Update cache if uv.lock changes
      
      - name: Build thirdweb-mcp
        run: |
          cd python/thirdweb-mcp
          uv build
      
      - name: Build thirdweb-ai
        run: |
          cd python/thirdweb-ai
          uv build
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: python/thirdweb-mcp/dist/ python/thirdweb-ai/dist/
